name: Auto Update JioTVPlus3

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Playlist 1
        run: |
          curl -L "https://raw.githubusercontent.com/sportlive18/jio-tv-auto-update-playlist/refs/heads/main/pocket.m3u" -o source1.m3u

      - name: Download Playlist 2
        run: |
          curl -L "https://raw.githubusercontent.com/maybetv/jojo/refs/heads/main/pocket.m3u" -o source2.m3u

      - name: Create JioTVPlus3
        run: |
          echo '#EXTM3U' > JioTVPlus3.m3u
          tail -n +2 source1.m3u >> JioTVPlus3.m3u
          tail -n +2 source2.m3u >> JioTVPlus3.m3u

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add JioTVPlus3.m3u

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update JioTVPlus3"
            git push
          fi
