name: Auto Update JioTVPlus 4-8

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:


permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # JioTVPlus4
      - name: Download JioTVPlus4
        run: |
          curl -fL "https://raw.githubusercontent.com/Kalyan123407/STBPLUS/refs/heads/main/streamflex_fresh.m3u" -o JioTVPlus4.m3u

      # JioTVPlus5
      - name: Download JioTVPlus5
        run: |
          curl -fL "https://raw.githubusercontent.com/purupc00-dev/Gmax-JioTV/refs/heads/main/Playlists/JioTV_S1.m3u" -o JioTVPlus5.m3u

      # JioTVPlus6
      - name: Download JioTVPlus6
        run: |
          curl -fL "https://raw.githubusercontent.com/amazeyourself/m3u/refs/heads/main/jtv.m3u" -o JioTVPlus6.m3u

      # JioTVPlus7
      - name: Download JioTVPlus7
        run: |
          curl -fL "https://raw.githubusercontent.com/pocket-tamil/m3u_source/refs/heads/main/strx.m3u" -o JioTVPlus7.m3u

      # JioTVPlus8
      - name: Download JioTVPlus8
        run: |
          curl -fL "https://raw.githubusercontent.com/qwerty180506/Geo/refs/heads/main/jiotv2.m3u" -o JioTVPlus8.m3u

      # Commit and Push
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add JioTVPlus4.m3u JioTVPlus5.m3u JioTVPlus6.m3u JioTVPlus7.m3u JioTVPlus8.m3u

          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "Auto update JioTVPlus 4-8"
            git push
          fi
